import type { Certification } from "./types";

/**
 * Curated mock certification catalog. In production this is replaced by the
 * Supabase/Prisma-backed directory; the shape stays identical so the
 * recommendation engine and UI don't change.
 */
export const CERTIFICATIONS: Certification[] = [
  {
    id: "pmp",
    name: "Project Management Professional",
    provider: "PMI",
    abbr: "PMP",
    industry: "project_management",
    difficulty: "advanced",
    builds: { project: 0.9, leadership: 0.6, business: 0.5, communication: 0.5 },
    durationWeeks: 16,
    examCost: 555,
    budgetBand: "high",
    salaryImpact: 22,
    saudiRelevance: 95,
    globalRelevance: 98,
    rating: 4.7,
    reviews: 18420,
    summary: {
      en: "The global gold standard for project leaders, recognised across every industry.",
      ar: "المعيار الذهبي العالمي لقادة المشاريع، معترف به في جميع القطاعات.",
    },
    outcomes: [
      { en: "Lead complex cross-functional projects", ar: "قيادة مشاريع معقدة متعددة الوظائف" },
      { en: "Master predictive & agile delivery", ar: "إتقان التسليم التنبؤي والرشيق" },
    ],
    tags: ["management", "delivery", "leadership"],
  },
  {
    id: "prince2",
    name: "PRINCE2 Practitioner",
    provider: "AXELOS",
    abbr: "PRINCE2",
    industry: "project_management",
    difficulty: "intermediate",
    builds: { project: 0.85, business: 0.4, leadership: 0.4 },
    durationWeeks: 8,
    examCost: 400,
    budgetBand: "medium",
    salaryImpact: 15,
    saudiRelevance: 78,
    globalRelevance: 85,
    rating: 4.4,
    reviews: 9200,
    summary: {
      en: "A process-driven method for controlled, scalable project governance.",
      ar: "منهجية قائمة على العمليات لحوكمة مشاريع منضبطة وقابلة للتوسع.",
    },
    outcomes: [
      { en: "Apply a tailored governance framework", ar: "تطبيق إطار حوكمة مخصص" },
      { en: "Control scope, risk and stages", ar: "التحكم في النطاق والمخاطر والمراحل" },
    ],
    tags: ["governance", "delivery"],
  },
  {
    id: "shrm-cp",
    name: "SHRM Certified Professional",
    provider: "SHRM",
    abbr: "SHRM-CP",
    industry: "hr",
    difficulty: "intermediate",
    builds: { leadership: 0.5, business: 0.5, communication: 0.7 },
    durationWeeks: 12,
    examCost: 410,
    budgetBand: "medium",
    salaryImpact: 18,
    saudiRelevance: 82,
    globalRelevance: 96,
    rating: 4.6,
    reviews: 12100,
    summary: {
      en: "Behavioural-competency HR credential trusted by employers worldwide.",
      ar: "شهادة موارد بشرية قائمة على الكفاءات السلوكية يثق بها أصحاب العمل عالميًا.",
    },
    outcomes: [
      { en: "Translate HR strategy into practice", ar: "ترجمة استراتيجية الموارد البشرية إلى ممارسة" },
      { en: "Lead people programmes with impact", ar: "قيادة برامج الموظفين بأثر ملموس" },
    ],
    tags: ["hr", "people", "strategy"],
  },
  {
    id: "phri",
    name: "Professional in Human Resources – International",
    provider: "HRCI",
    abbr: "PHRi",
    industry: "hr",
    difficulty: "intermediate",
    builds: { business: 0.5, communication: 0.6, leadership: 0.4 },
    durationWeeks: 10,
    examCost: 495,
    budgetBand: "medium",
    salaryImpact: 16,
    saudiRelevance: 88,
    globalRelevance: 80,
    rating: 4.3,
    reviews: 5400,
    summary: {
      en: "Operational HR credential popular across the GCC talent market.",
      ar: "شهادة موارد بشرية تشغيلية شائعة في سوق المواهب الخليجي.",
    },
    outcomes: [
      { en: "Own core HR operations end-to-end", ar: "إدارة عمليات الموارد البشرية الأساسية بالكامل" },
      { en: "Align policy with labour regulation", ar: "مواءمة السياسات مع أنظمة العمل" },
    ],
    tags: ["hr", "operations", "gcc"],
  },
  {
    id: "cfa",
    name: "Chartered Financial Analyst",
    provider: "CFA Institute",
    abbr: "CFA",
    industry: "finance",
    difficulty: "expert",
    builds: { business: 0.9, aiData: 0.4, technical: 0.4 },
    durationWeeks: 40,
    examCost: 1200,
    budgetBand: "high",
    salaryImpact: 35,
    saudiRelevance: 84,
    globalRelevance: 99,
    rating: 4.8,
    reviews: 22400,
    summary: {
      en: "The most respected credential in investment management and analysis.",
      ar: "الشهادة الأكثر احترامًا في إدارة الاستثمار والتحليل المالي.",
    },
    outcomes: [
      { en: "Value assets and build portfolios", ar: "تقييم الأصول وبناء المحافظ" },
      { en: "Apply ethical, global standards", ar: "تطبيق المعايير الأخلاقية العالمية" },
    ],
    tags: ["finance", "investment", "analysis"],
  },
  {
    id: "cma",
    name: "Certified Management Accountant",
    provider: "IMA",
    abbr: "CMA",
    industry: "finance",
    difficulty: "advanced",
    builds: { business: 0.8, aiData: 0.3, leadership: 0.3 },
    durationWeeks: 28,
    examCost: 850,
    budgetBand: "high",
    salaryImpact: 28,
    saudiRelevance: 90,
    globalRelevance: 92,
    rating: 4.6,
    reviews: 15200,
    summary: {
      en: "Bridges accounting and strategy for finance leaders in industry.",
      ar: "يربط المحاسبة بالاستراتيجية لقادة المالية في القطاعات.",
    },
    outcomes: [
      { en: "Drive planning, budgeting & analytics", ar: "قيادة التخطيط والموازنة والتحليلات" },
      { en: "Support strategic decision-making", ar: "دعم اتخاذ القرار الاستراتيجي" },
    ],
    tags: ["finance", "accounting", "strategy"],
  },
  {
    id: "aws-saa",
    name: "AWS Certified Solutions Architect – Associate",
    provider: "Amazon Web Services",
    abbr: "AWS SAA",
    industry: "cloud",
    difficulty: "intermediate",
    builds: { technical: 0.85, aiData: 0.4, project: 0.3 },
    durationWeeks: 10,
    examCost: 150,
    budgetBand: "low",
    salaryImpact: 26,
    saudiRelevance: 92,
    globalRelevance: 97,
    rating: 4.7,
    reviews: 31200,
    summary: {
      en: "Design resilient, cost-optimised systems on the leading cloud platform.",
      ar: "تصميم أنظمة مرنة ومحسّنة التكلفة على منصة السحابة الرائدة.",
    },
    outcomes: [
      { en: "Architect scalable cloud solutions", ar: "تصميم حلول سحابية قابلة للتوسع" },
      { en: "Optimise for cost and reliability", ar: "التحسين من أجل التكلفة والموثوقية" },
    ],
    tags: ["cloud", "architecture", "aws"],
  },
  {
    id: "az-900",
    name: "Microsoft Azure Fundamentals",
    provider: "Microsoft",
    abbr: "AZ-900",
    industry: "cloud",
    difficulty: "beginner",
    builds: { technical: 0.5, aiData: 0.3, business: 0.2 },
    durationWeeks: 4,
    examCost: 99,
    budgetBand: "low",
    salaryImpact: 10,
    saudiRelevance: 80,
    globalRelevance: 88,
    rating: 4.5,
    reviews: 26800,
    summary: {
      en: "An accessible entry point into cloud concepts and the Azure ecosystem.",
      ar: "نقطة انطلاق سهلة لمفاهيم السحابة ومنظومة Azure.",
    },
    outcomes: [
      { en: "Understand core cloud concepts", ar: "فهم مفاهيم السحابة الأساسية" },
      { en: "Navigate Azure services confidently", ar: "التنقل بين خدمات Azure بثقة" },
    ],
    tags: ["cloud", "fundamentals", "azure"],
  },
  {
    id: "cissp",
    name: "Certified Information Systems Security Professional",
    provider: "ISC2",
    abbr: "CISSP",
    industry: "cybersecurity",
    difficulty: "expert",
    builds: { technical: 0.8, leadership: 0.4, business: 0.4 },
    durationWeeks: 24,
    examCost: 749,
    budgetBand: "high",
    salaryImpact: 32,
    saudiRelevance: 89,
    globalRelevance: 98,
    rating: 4.7,
    reviews: 19800,
    summary: {
      en: "The benchmark credential for senior security leaders and architects.",
      ar: "الشهادة المرجعية لقادة ومهندسي الأمن السيبراني الكبار.",
    },
    outcomes: [
      { en: "Design enterprise security programmes", ar: "تصميم برامج الأمن المؤسسي" },
      { en: "Govern risk across eight domains", ar: "حوكمة المخاطر عبر ثمانية مجالات" },
    ],
    tags: ["security", "governance", "leadership"],
  },
  {
    id: "comptia-sec",
    name: "CompTIA Security+",
    provider: "CompTIA",
    abbr: "Security+",
    industry: "cybersecurity",
    difficulty: "intermediate",
    builds: { technical: 0.7, project: 0.2 },
    durationWeeks: 8,
    examCost: 392,
    budgetBand: "medium",
    salaryImpact: 18,
    saudiRelevance: 83,
    globalRelevance: 90,
    rating: 4.5,
    reviews: 24100,
    summary: {
      en: "Foundational, vendor-neutral security certification for practitioners.",
      ar: "شهادة أمنية تأسيسية محايدة تجاه المورّدين للممارسين.",
    },
    outcomes: [
      { en: "Handle threats, attacks and hardening", ar: "التعامل مع التهديدات والهجمات والتحصين" },
      { en: "Meet baseline compliance needs", ar: "تلبية متطلبات الامتثال الأساسية" },
    ],
    tags: ["security", "fundamentals"],
  },
  {
    id: "google-da",
    name: "Google Data Analytics Professional Certificate",
    provider: "Google",
    abbr: "Google DA",
    industry: "data_ai",
    difficulty: "beginner",
    builds: { aiData: 0.7, technical: 0.4, business: 0.3 },
    durationWeeks: 12,
    examCost: 234,
    budgetBand: "low",
    salaryImpact: 16,
    saudiRelevance: 76,
    globalRelevance: 89,
    rating: 4.6,
    reviews: 41200,
    summary: {
      en: "A hands-on launchpad into analytics with SQL, spreadsheets and Tableau.",
      ar: "منصة انطلاق عملية إلى التحليلات باستخدام SQL والجداول وTableau.",
    },
    outcomes: [
      { en: "Clean, analyse and visualise data", ar: "تنظيف البيانات وتحليلها وتصويرها" },
      { en: "Tell decisions with dashboards", ar: "دعم القرارات بلوحات المعلومات" },
    ],
    tags: ["data", "analytics", "entry"],
  },
  {
    id: "tf-dev",
    name: "TensorFlow Developer Certificate",
    provider: "Google",
    abbr: "TF Dev",
    industry: "data_ai",
    difficulty: "advanced",
    builds: { aiData: 0.9, technical: 0.6 },
    durationWeeks: 14,
    examCost: 100,
    budgetBand: "low",
    salaryImpact: 24,
    saudiRelevance: 70,
    globalRelevance: 84,
    rating: 4.3,
    reviews: 8600,
    summary: {
      en: "Prove you can build and train deep-learning models in production.",
      ar: "أثبت قدرتك على بناء وتدريب نماذج التعلم العميق في الإنتاج.",
    },
    outcomes: [
      { en: "Build neural networks with Keras", ar: "بناء الشبكات العصبية باستخدام Keras" },
      { en: "Handle vision, text and sequences", ar: "التعامل مع الرؤية والنص والتسلسلات" },
    ],
    tags: ["ai", "ml", "deep-learning"],
  },
  {
    id: "aws-mls",
    name: "AWS Certified Machine Learning – Specialty",
    provider: "Amazon Web Services",
    abbr: "AWS MLS",
    industry: "data_ai",
    difficulty: "expert",
    builds: { aiData: 0.9, technical: 0.7, business: 0.3 },
    durationWeeks: 18,
    examCost: 300,
    budgetBand: "medium",
    salaryImpact: 30,
    saudiRelevance: 74,
    globalRelevance: 86,
    rating: 4.4,
    reviews: 7300,
    summary: {
      en: "Operationalise machine learning on AWS at enterprise scale.",
      ar: "تشغيل التعلم الآلي على AWS بمقياس مؤسسي.",
    },
    outcomes: [
      { en: "Engineer end-to-end ML pipelines", ar: "هندسة مسارات تعلم آلي متكاملة" },
      { en: "Deploy and monitor models", ar: "نشر النماذج ومراقبتها" },
    ],
    tags: ["ai", "ml", "cloud"],
  },
  {
    id: "csm",
    name: "Certified ScrumMaster",
    provider: "Scrum Alliance",
    abbr: "CSM",
    industry: "project_management",
    difficulty: "beginner",
    builds: { project: 0.6, leadership: 0.4, communication: 0.5 },
    durationWeeks: 3,
    examCost: 1000,
    budgetBand: "high",
    salaryImpact: 14,
    saudiRelevance: 80,
    globalRelevance: 88,
    rating: 4.4,
    reviews: 20100,
    summary: {
      en: "Kick-start agile delivery and servant-leadership of Scrum teams.",
      ar: "انطلق في التسليم الرشيق والقيادة الخادمة لفرق سكرم.",
    },
    outcomes: [
      { en: "Facilitate Scrum events well", ar: "تيسير فعاليات سكرم بفعالية" },
      { en: "Coach teams toward flow", ar: "توجيه الفرق نحو الانسيابية" },
    ],
    tags: ["agile", "scrum", "delivery"],
  },
  {
    id: "google-pm",
    name: "Google Project Management Certificate",
    provider: "Google",
    abbr: "Google PM",
    industry: "project_management",
    difficulty: "beginner",
    builds: { project: 0.6, communication: 0.4, business: 0.3 },
    durationWeeks: 10,
    examCost: 234,
    budgetBand: "low",
    salaryImpact: 12,
    saudiRelevance: 72,
    globalRelevance: 82,
    rating: 4.6,
    reviews: 33400,
    summary: {
      en: "An affordable, practical on-ramp into professional project management.",
      ar: "مدخل عملي وميسور التكلفة إلى إدارة المشاريع الاحترافية.",
    },
    outcomes: [
      { en: "Run projects across life-cycles", ar: "إدارة المشاريع عبر دورات حياتها" },
      { en: "Blend agile and traditional tools", ar: "الدمج بين الأدوات الرشيقة والتقليدية" },
    ],
    tags: ["management", "entry", "agile"],
  },
  {
    id: "cips",
    name: "CIPS Diploma in Procurement & Supply",
    provider: "CIPS",
    abbr: "CIPS",
    industry: "supply_chain",
    difficulty: "intermediate",
    builds: { business: 0.6, project: 0.4, communication: 0.3 },
    durationWeeks: 20,
    examCost: 700,
    budgetBand: "high",
    salaryImpact: 20,
    saudiRelevance: 86,
    globalRelevance: 84,
    rating: 4.3,
    reviews: 6100,
    summary: {
      en: "The leading global standard for procurement and supply professionals.",
      ar: "المعيار العالمي الرائد لمحترفي المشتريات والإمداد.",
    },
    outcomes: [
      { en: "Run strategic sourcing & contracts", ar: "إدارة التوريد الاستراتيجي والعقود" },
      { en: "Manage supplier relationships", ar: "إدارة علاقات المورّدين" },
    ],
    tags: ["procurement", "supply-chain"],
  },
  {
    id: "cscp",
    name: "APICS Certified Supply Chain Professional",
    provider: "ASCM",
    abbr: "CSCP",
    industry: "supply_chain",
    difficulty: "advanced",
    builds: { business: 0.6, aiData: 0.3, project: 0.4 },
    durationWeeks: 22,
    examCost: 1100,
    budgetBand: "high",
    salaryImpact: 23,
    saudiRelevance: 82,
    globalRelevance: 90,
    rating: 4.5,
    reviews: 7800,
    summary: {
      en: "End-to-end supply-chain mastery from planning to delivery.",
      ar: "إتقان سلسلة الإمداد من التخطيط حتى التسليم.",
    },
    outcomes: [
      { en: "Optimise global supply networks", ar: "تحسين شبكات الإمداد العالمية" },
      { en: "Balance cost, risk and service", ar: "الموازنة بين التكلفة والمخاطر والخدمة" },
    ],
    tags: ["supply-chain", "operations"],
  },
  {
    id: "google-ux",
    name: "Google UX Design Certificate",
    provider: "Google",
    abbr: "Google UX",
    industry: "technology",
    difficulty: "beginner",
    builds: { technical: 0.4, communication: 0.5, aiData: 0.2 },
    durationWeeks: 16,
    examCost: 234,
    budgetBand: "low",
    salaryImpact: 15,
    saudiRelevance: 68,
    globalRelevance: 80,
    rating: 4.6,
    reviews: 28900,
    summary: {
      en: "Build a portfolio and the craft of user-centred product design.",
      ar: "ابنِ معرض أعمال وأتقن تصميم المنتجات المتمحور حول المستخدم.",
    },
    outcomes: [
      { en: "Run research-to-prototype cycles", ar: "إدارة دورات من البحث إلى النموذج" },
      { en: "Design accessible interfaces", ar: "تصميم واجهات سهلة الوصول" },
    ],
    tags: ["design", "ux", "product"],
  },
  {
    id: "meta-marketing",
    name: "Meta Marketing Analytics Professional Certificate",
    provider: "Meta",
    abbr: "Meta MA",
    industry: "marketing",
    difficulty: "intermediate",
    builds: { aiData: 0.5, business: 0.5, communication: 0.4 },
    durationWeeks: 14,
    examCost: 234,
    budgetBand: "low",
    salaryImpact: 17,
    saudiRelevance: 71,
    globalRelevance: 82,
    rating: 4.4,
    reviews: 11200,
    summary: {
      en: "Turn marketing data into strategy, attribution and measurable growth.",
      ar: "حوّل بيانات التسويق إلى استراتيجية وإسناد ونمو قابل للقياس.",
    },
    outcomes: [
      { en: "Measure campaigns with rigour", ar: "قياس الحملات بدقة" },
      { en: "Optimise spend across channels", ar: "تحسين الإنفاق عبر القنوات" },
    ],
    tags: ["marketing", "analytics", "growth"],
  },
  {
    id: "chfp",
    name: "Certified Healthcare Financial Professional",
    provider: "HFMA",
    abbr: "CHFP",
    industry: "healthcare",
    difficulty: "advanced",
    builds: { business: 0.7, communication: 0.3, project: 0.3 },
    durationWeeks: 18,
    examCost: 600,
    budgetBand: "high",
    salaryImpact: 21,
    saudiRelevance: 66,
    globalRelevance: 78,
    rating: 4.2,
    reviews: 3200,
    summary: {
      en: "Financial leadership tailored to the healthcare provider landscape.",
      ar: "قيادة مالية مصممة لبيئة مقدّمي الرعاية الصحية.",
    },
    outcomes: [
      { en: "Manage healthcare economics", ar: "إدارة اقتصاديات الرعاية الصحية" },
      { en: "Improve revenue-cycle outcomes", ar: "تحسين نتائج دورة الإيرادات" },
    ],
    tags: ["healthcare", "finance"],
  },
  {
    id: "genai-arch",
    name: "Generative AI Leader Certificate",
    provider: "Draaya Academy",
    abbr: "GenAI",
    industry: "data_ai",
    difficulty: "intermediate",
    builds: { aiData: 0.8, leadership: 0.5, business: 0.5 },
    durationWeeks: 8,
    examCost: 320,
    budgetBand: "medium",
    salaryImpact: 27,
    saudiRelevance: 93,
    globalRelevance: 85,
    rating: 4.7,
    reviews: 2100,
    summary: {
      en: "Lead responsible generative-AI adoption across teams and functions.",
      ar: "قُد التبني المسؤول للذكاء الاصطناعي التوليدي عبر الفرق والوظائف.",
    },
    outcomes: [
      { en: "Frame AI use-cases and ROI", ar: "صياغة حالات استخدام الذكاء الاصطناعي وعائدها" },
      { en: "Govern AI risk and ethics", ar: "حوكمة مخاطر وأخلاقيات الذكاء الاصطناعي" },
    ],
    tags: ["ai", "leadership", "strategy"],
  },
];

export function getCertification(id: string): Certification | undefined {
  return CERTIFICATIONS.find((c) => c.id === id);
}
